# Generated by Django 5.2.1 on 2025-06-03 05:10

import app.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
                ('objects', app.managers.UsuarioManager()),
            ],
        ),
    ]
