# Generated by Django 5.2.1 on 2025-06-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuarios_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nac',
            field=models.DateField(blank=True),
        ),
    ]
