# Generated by Django 5.2.1 on 2025-06-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuarios_fecha_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
