# Generated by Django 5.2.2 on 2025-06-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuarios_fecha_nac'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidente', models.CharField(choices=[('robo', 'Robo'), ('secuestro', 'Secuestro'), ('vandalismo', 'Vandalismo'), ('área desolada', 'Área desolada'), ('violación', 'Violación'), ('asesinato', 'Asesinato'), ('extorsión', 'Extorsión')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
