# Generated by Django 5.2.2 on 2025-06-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reporteincidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteincidente',
            name='tipo_incidente',
            field=models.CharField(choices=[('Robo', 'Robo'), ('Homicidio', 'Homicidio'), ('Extorsion', 'Extorsión'), ('Secuestro', 'Secuestro')], max_length=50),
        ),
    ]
