# Generated by Django 5.2.1 on 2025-06-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuarios_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidente', models.CharField(choices=[('Robo', 'Robo'), ('Homicidio', 'Homicidio'), ('Extorsion', 'Extorsion'), ('Secuestro', 'Secuestro')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
